### ISSUE TITLE
RepositoryToken is invalid. Provided token has invalid permissions and cannot be used to setup Github Action CI/CD. Admin rights are required for the repository.

### ISSUE THREAD

**Issue by ParageeSharma** [education/codespaces-project-template-js#54]
RepositoryToken is invalid. Provided token has invalid permissions and cannot be used to setup Github Action CI/CD. Admin rights are required for the repository.

**Comment by saragibby** [comment]
Hi @ParageeSharma! It sounds like you may be trying to set a GitHub Action against this repository, instead of your own. To create your own version of this, and set up Actions to deploy, you will need to start by forking this to your own (https://github.com/education/codespaces-project-template-js#create-your-portfolio). 

I'm going to close this issue, but if you have any questions or issues, please feel free to open a new GitHub issue or discussion.
